const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' });
  const p = await b.newPage();
  await p.goto('https://arc-bench.com/login', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await p.waitForTimeout(1200);
  await p.fill('#login-email', '2436448088@qq.com');
  await p.fill('#login-password', 'xbao2436');
  await p.click('button:has-text("Login")');
  await p.waitForTimeout(3000);
  await p.goto('https://arc-bench.com/competitions/hackathon', { waitUntil: 'domcontentloaded', timeout: 90000 });
  await p.waitForTimeout(6000);
  console.log('url:', p.url());
  const body = await p.evaluate(() => document.body.innerText.replace(/\n{2,}/g, '\n'));
  console.log('=== body ===');
  console.log(body.slice(0, 2500));
  const links = await p.evaluate(() => Array.from(document.querySelectorAll('a')).map(a => a.getAttribute('href')).filter(Boolean));
  console.log('LINKCOUNT', links.length, JSON.stringify(links.filter(h => h.includes('run') || h.includes('submission')).slice(0, 20)));
  await p.screenshot({ path: 'g2/runs/site-hackathon.png', fullPage: true });
  await b.close();
})().catch(e => { console.error('FAILED', e.message); process.exit(1); });